### ISSUE TITLE
Building with llvm 3.6 broke after revision 4f09ca6d0de55ebf792858f50ffc65d9cc1c8613

### ISSUE THREAD

**Issue by v-fox** [llvm-mirror/libclc#3]
Now it fails with:
```
[   39s] /usr/bin/clang -MMD -MF nvptx64--nvidiacl/lib/subnormal_config.cl.bc.d -target nvptx64--nvidiacl -I`dirname ./generic/lib/subnormal_config.cl` -I./generic/include -fno-builtin -Dcl_clang_storage_class_specifiers -Dcl_khr_fp64 -Dcles_khr_int64 -D__CLC_INTERNAL -emit-llvm -c -o nvptx64--nvidiacl/lib/subnormal_config.cl.bc ./generic/lib/subnormal_config.cl
[   39s] ./utils/prepare-builtins.cpp:56:28: error: member reference type 'typename std::remove_reference<Module *>::type' (aka 'llvm::Module *') is a pointer; maybe you meant to use '->'?
[   39s]       M = ModuleOrErr.get().get();
[   39s]           ~~~~~~~~~~~~~~~~~^
[   39s]                            ->
[   39s] ./utils/prepare-builtins.cpp:56:29: error: no member named 'get' in 'llvm::Module'
[   39s]       M = ModuleOrErr.get().get();
[   39s]           ~~~~~~~~~~~~~~~~~ ^
[   40s] 2 errors generated.
[   40s] Makefile:8: recipe for target 'utils/prepare-builtins.o' failed
[   40s] make: *** [utils/prepare-builtins.o] Error 1
[   40s] make: *** Waiting for unfinished jobs....
```
